version: "3.3"
services:
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
    command: nsqd
  node:
    image: node:8.9.3-alpine
    volumes:
      - "./:/opt"
    depends_on:
      - "nsqd"
    environment:
      WD40_PUB_COUNT: 0
      WD40_SUB_COUNT: 0
    working_dir: /opt
    command: npm start
